# Generated by Django 5.2.7 on 2025-11-09 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import common.models.base_model


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_gamereport_gamereportadvice_report_gamereport_report_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportBotToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "token",
                    models.CharField(
                        help_text="BOT 인증을 위한 토큰 문자열", max_length=100, unique=True, verbose_name="토큰"
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bot_tokens",
                        to="reports.report",
                        verbose_name="리포트",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="리포트 소유 사용자 (캐싱용)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bot_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "리포트 BOT 토큰",
                "verbose_name_plural": "리포트 BOT 토큰",
                "db_table": "report_bot_tokens",
                "ordering": ["-created_at"],
            },
            managers=[
                ("objects", common.models.base_model.BaseModelManager()),
            ],
        ),
    ]
